[package]
name = "tui_stopwatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
core_stopwatch = { path = "../core_stopwatch" }
once_cell = "1.18.0"
